### ISSUE TITLE
GitHub action

### ISSUE THREAD

**Issue by mgibeau** [byCedric/semantic-release-expo#85]
I've created a GitHub action around this project, do you think it would make sense to add it to this repository, or would you rather keep it separate? 

See current (crude) implementation here: https://github.com/mgibeau/semantic-release-expo-github-action

Happy to discuss, etc even transfer over if you prefer that.

**Comment by byCedric** [comment]
Hi again 😄 @mgibeau! It looks awesome, this is definitely something I really want to support too! Right now, I'm keeping an eye on the [GitHub Action for Semantic Release](https://github.com/semantic-release/semantic-release/issues/974) itself. They are evaluating to see if they can create one, which I think would have my preference over creating one here. But if this turns out blank or they think it wouldn't be a good thing, let's add your code to this repo! Thanks, again! ❤️

**Comment by mgibeau** [comment]
Cool, that makes sense, I would certainly use their canonical version as well when they release it, thanks for sharing this! I'm going to close this issue for now then 😄
